name: Haskell CI

on:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build EwHaskell
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.2"]
        ghc: ["8.10.4"]

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: Build
      run: |
        cd haskell
        cabal v2-build --enable-tests --enable-benchmarks

  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.2"]
        ghc: ["8.10.4"]
    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: BasicTypes
      run: |
        cd haskell
        cabal run ewhaskell-test --enable-tests -- -m "BasicTypes"

    - name: ObjectTypes
      run: |
        cd haskell
        cabal run ewhaskell-test --enable-tests -- -m "ObjectTypes"

    - name: CodeWars
      run: |
        cd haskell
        cabal run ewhaskell-test --enable-tests -- -m "CodeWars"

  run:
    name: Running DataTypes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.2"]
        ghc: ["8.10.4"]
    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    name: Build DataTypes
    run: |
      cd haskell
      make datatypes
      build/datatypes